spring:
  application:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

foo: foo version 4
test: ceshi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
